### ISSUE TITLE
Mission Statement Text

### ISSUE THREAD

**Issue by moodzyy** [undeclareddev/undeclared-homepage#3]
> Undeclared Development is an international development group formed from a shared desire of self improvement. Our membership is comprised of web developers of varied backgrounds ranging from novice coders to seasoned veterans. 
> 
> Undeclared Development’s goal is to simulate a professional, team-based development environment while creating applications that have real world value. Regardless of individual skill, all members will be fostering new talents in order to find future success in the workforce.

I made a rough draft of a potential mission statement. I wanted to get everyone's thoughts before I went through the effort of making a pull request. Let me know if you have any ideas or if I need to make any edits.

**Comment by patrickblackjr** [comment]
I'd say go ahead and submit a PR.

**Comment by patrickblackjr** [comment]
See #7

**Comment by patrickblackjr** [comment]
Done! Thanks!
